-- Kosmos Service Supabase bootstrap.
--
-- Source of truth: files in supabase/migrations/.
-- Apply them in order in a separate Supabase project for this repository:
--
-- 1. supabase/migrations/20260605_000001_kosmos_cloud_core.sql
-- 2. supabase/migrations/20260606_kosmos_realtime.sql
--
-- This file exists as the project entrypoint, so the schema location is visible
-- next to the repository root and can be pasted into Supabase SQL Editor by
-- opening the migration files above. Do not paste SQL from the Razberemsia
-- project and do not reuse its project URL, anon key, repo name, or secrets.
